ansible_user: "{{ lookup('hashi_vault', 'secret=spg/invtools-stg/generic/ubuntu_jenkins_node:admin_user')}}"
ansible_password: "{{ lookup('hashi_vault', 'secret=spg/invtools-stg/generic/ubuntu_jenkins_node:admin_password')}}"
ansible_become: true
ansible_become_user: root
ansible_become_pass: "{{ lookup('hashi_vault', 'secret=spg/invtools-stg/generic/ubuntu_jenkins_node:admin_password')}}"

git_token: "{{ lookup('hashi_vault', 'secret=spg/invtools-stg/generic/ubuntu_splunklight_node:git_token')}}"
artifactory_token: "{{ lookup('hashi_vault', 'secret=spg/invtools-stg/generic/ubuntu_splunklight_node:artifactory_token')}}"

splunk:
  src: https://art-bobcat.autodesk.com/artifactory/team-dlstools-generic/Tools/Splunk/splunk-7.1.3-51d9cac7b837-Linux-x86_64.tgz
  dest: /opt
  usr: admin
  psw: "{{ lookup('hashi_vault', 'secret=spg/invtools-stg/generic/ubuntu_splunklight_node:splunk_psw')}}"
  guest: Autodesk
  guest_psw: Autodesk
