ansible_user: Administrator
ansible_password: "{{ lookup('hashi_vault', 'secret=spg/invtools-prd/generic/jenkins-nodes/accounts:Administrator')}}"
ansible_port: 5986
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore
validate_certs: false
ansible_winrm_operation_timeout_sec: 120
ansible_winrm_read_timeout_sec: 150
